name: Staging Release
run-name: Env Shell Script
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:
  generate-env-file:
    runs-on: self-hosted
    steps:
      - run: echo "🚀 working directory ${{ github.workspace}}."
      - name: Generate cypress.env.json file
        run: ./generate-cypress-env-file.sh
        shell: bash
