name: Staging Release
run-name: Env Shell Script
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:
  generate-env-file:
    runs-on: self-hosted
    steps:
      - name: Check if cypress.env.json file exists
        run: |
          if [ ! -f "cypress.env.json" ]; then
           echo '{"userFree": {"email": "cypress+infra+27@gmail.com", "password": "123456"}, "userPaid": {"email": "cypress+48@test.test", "password": "suncica"}, "userRelease": {"email": "cypress+40@test.test", "password": "suncica"}}' > cypress.env.json
          fi
        working-directory: ./ # set the working directory to the root of your project
      - name: Create JSON file
        run: |
          echo '{"key": "value"}' > file.json
        working-directory: .
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.MY_JSON }}
          dir: "."
      - name: Print current directory
        run: echo "Current directory is $(pwd)"
      - name: Print files in directory
        run: ls
      - name: Print credentials.json
        run: |
          cat credentials.json
        working-directory: .
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Print credentials.json one more time
        run: |
          cat credentials.json
        working-directory: ${{ github.workspace }}

      - name: Test JSON file creation
        run: |
          if [ -f "file.json" ]; then
            echo "File created successfully"
            cat file.json
            cat credentials.json
          else
            echo "File creation failed"
          fi
        working-directory: .
  generate-random-string:
    runs-on: self-hosted
    steps:
      - name: Generate random string
        id: random-string
        uses: actions/github-script@v5
        with:
          script: |
            const randomString = Math.random().toString(36).substring(7);
            console.log(`::set-output name=randomString::${randomString}`);
      - name: Generate random string get
        id: random-string-get
        run: echo "::set-output name=value::$(openssl rand -hex 4)"

  create-json:
    runs-on: ubuntu-latest
    needs: generate-random-string
    steps:
      - name: Create JSON file
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: |
            {
              "userFree": {
                "email": "cypress+ci+cd+${{ needs.generate-random-string.outputs.randomString }}@gmail.com",
                "password": "123456"
              }
            }
          dir: "."
      - name: Generate JSON
        id: generate-json
        run: |
          echo '{"userFree": {"email": "cypress+ci+${{ steps.random-string.outputs.value }}@gmail.com", "password": "123456"}}' > credentials.json
      - name: Print JSON
        run: cat credentials.json
