name: Staging Release
run-name: Env Shell Script
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:
  generate-env-file:
    runs-on: self-hosted
    steps:
      - name: Generate Cypress Environment File
        run: ./.github/scripts/generate-cypress-env-file.sh
