name: Staging Release
run-name: Create cypress.env.json FILE
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:


  create-json:
    runs-on: self-hosted
    steps:
      - name: Generate JSON
        id: generate-json
        run: |
          if [ -f "cypress.env.json" ]; then
           echo "Creating cypress.env.json file"
           echo '{
             "userFree": {
               "email": "cypress+ci+'$(openssl rand -hex 4)'@gmail.com",
               "password": "123456"
             },
             "userPaid": {
               "email": "cypress+48@test.test",
               "password": "suncica"
             },
             "userRelease": {
               "email": "cypress+40@test.test",
               "password": "suncica"
             }
           }' > cypress.env.json
           else
           echo "Cypress.env.json already exists"
          fi
      - name: Print JSON
        run: cat cypress.env.json
