name: Staging Release
run-name: Env Shell Script
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:
  create-json:
    runs-on: self-hosted
    steps:
      - name: Check if scripts/generate-json.sh exists
        run: |
          if [ -f "./scripts/generate-json.sh" ]; then
            echo "generate-json.sh exists"
          else
            echo "generate-json.sh does not exist"
          fi
      - name: Check if ./generate-json.sh exists
        run: |
          if [ -f "./generate-json.sh" ]; then
            echo "generate-json.sh exists"
          else
            echo "generate-json.sh does not exist"
          fi
        working-directory: ./workflows
      - name: Check if scripts/generate-json.sh exists
        run: |
          if [ -f "./scripts/generate-json123132.sh" ]; then
            echo "generate-json.sh exists"
          else
            echo "generate-json.sh does not exist"
          fi
      - name: Generate JSON
        id: generate-json
        run: ./scripts/generate-json.sh
        shell: bash
      - name: Print JSON
        run: cat cypress.env.json
