name: Staging Release
run-name: Env Shell Script
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:


  create-json:
    runs-on: self-hosted
    steps:
      - name: Generate JSON
        id: generate-json
        run: ./generate-json.sh
      - name: Print JSON
        run: cat cypress.env.json
