name: Staging Release
run-name: Env Shell Script
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:
  generate-env-file:
    runs-on: self-hosted
    steps:
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "test.json"
          json: ${{ secrets.MY_JSON }}
          dir: "."
      - name: Read contents of test.json
        run: cat test.json
        working-directory: .
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Print credentials.json one more time
        run: |
          cat credentials.json
        working-directory: ${{ github.workspace }}

      - name: Test JSON file creation
        run: |
          if [ -f "file.json" ]; then
            echo "File created successfully"
            cat file.json
            cat credentials.json
          else
            echo "File creation failed"
          fi
        working-directory: .

  create-json:
    runs-on: self-hosted
    steps:
      - name: Generate JSON
        id: generate-json
        run: |
          if [ -f "cypress.env.json" ]; then
           echo "Creating cypress.env.json file"
           echo '{
             "userFree": {
               "email": "cypress+ci+'$(openssl rand -hex 4)'@gmail.com",
               "password": "123456"
             },
             "userPaid": {
               "email": "cypress+48@test.test",
               "password": "suncica"
             },
             "userRelease": {
               "email": "cypress+40@test.test",
               "password": "suncica"
             }
           }' > cypress.env.json
           else
           echo "Cypress.env.json already exists"
          fi
      - name: Print JSON
        run: cat cypress.env.json
