name: Staging Release
run-name: Env Shell Script
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:
  generate-env-file:
    runs-on: self-hosted
    steps:
      - name: Check if cypress.env.json file exists
        run: |
          if [ ! -f "cypress.env.json" ]; then
           echo '{"userFree": {"email": "cypress+infra+27@gmail.com", "password": "123456"}, "userPaid": {"email": "cypress+48@test.test", "password": "suncica"}, "userRelease": {"email": "cypress+40@test.test", "password": "suncica"}}' > cypress.env.json
          fi
        working-directory: ./ # set the working directory to the root of your project
      - name: Create JSON file
        run: |
          echo '{"key": "value"}' > file.json
        working-directory: .
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.MY_JSON }}
      - name: Test JSON file creation
        run: |
          if [ -f "file.json" ]; then
            echo "File created successfully"
          else
            echo "File creation failed"
          fi
        working-directory: .
