name: Staging Release
run-name: Env Shell Script
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:
  generate-env-file:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x /generate-cypress-env-file.sh
          /generate-cypress-env-file.sh
        shell: bash
