name: Staging Release
run-name: Cypress CI/CD - Staging Release
on:
  push:
    branches:
      - release/*
      - hotfix/*
jobs:
  generate-env-file:
    runs-on: self-hosted
    steps:
      - name: Generate cypress.env.json file
        run: ./generate-cypress-env-file.sh
        shell: bash
        working-directory: ${{ github.workspace }}


