name: Example workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate cypress env json file
        run: |
          chmod +x ./.github/scripts/generate-cypress-env-json.sh
          ./.github/scripts/generate-cypress-env-json.sh ${{ github.workspace }}
        shell: bash

      - name: Print Repository Contents
        run: |
          cd ${{ github.workspace }}
          ls -la
