name: Example workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Call test script
        run: |
          chmod +x ./.github/scripts/test.sh
          ./.github/scripts/test.sh
      - name: Call print script
        run: |
          chmod +x ./.github/scripts/print.sh
          ./.github/scripts/print.sh ${{ github.workspace }}

      - name: Print Repository Contents
        run: |
          cd ${{ github.workspace }}
          ls -la
