name: Example workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: List files in scripts directory
        run: ls -l ./.github/scripts/test.sh
