name: Example workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print Repository Contents
        run: |
          cd ${{ github.workspace }}
          ls -la

      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        shell: bash

      - name: Find script file
        run: find ${{ github.workspace }} -name "test.sh"
