name: Example workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run script from file
        run: ./.github/test.sh
        shell: bash

      - name: Where am I
        run: pwd
      - name: List files
        run: |
          ls -la ${{ github.workspace }}
    #   - name: Run test script
    #     run: bash .github/scripts/test.sh
    #   - name: List files in scripts directory
    #     run: ls -l ./.github/scripts/test.sh
