name: Example workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Where am I
        run: pwd
      - name: List files
        run: |
          ls -la ${{ github.workspace }}
    #   - name: Run test script
    #     run: bash .github/scripts/test.sh
    #   - name: List files in scripts directory
    #     run: ls -l ./.github/scripts/test.sh
