name: Example workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print Repository Contents
        run: |
          cd ${{ github.workspace }}
          ls -la

      - name: Run Script
        run: |
          cd ${{ github.workspace }}/.github/scripts
          sh test.sh
